import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import StoreProvider from "@/store/StoreProvider";
import Navbar from "@/common/_components/Navbar";
import RefreshToken from "@/common/_components/RefreshToken";
import QueryProvider from "./QueryProvider";

const manrope = Manrope({
    variable: "--font-manrope",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true} data-qb-installed="true">
            <StoreProvider>
                <body className={cn(`antialiased`, manrope.variable)}>
                    <QueryProvider>
                        <RefreshToken>
                            <Navbar />
                            <main>{children}</main>
                        </RefreshToken>
                    </QueryProvider>
                </body>
            </StoreProvider>
        </html>
    );
}
